In [23]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import ParameterGrid
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import string
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer   # “Term Frequency times Inverse Document Frequency”
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB       # Multinomial Naive Bayes, supposedly goes well with the data from the transformer
from sklearn.svm import svm
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_fscore_support
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, classification_report, confusion_matrix

ImportError: cannot import name 'svm'

In [24]:
df = pd.read_csv('MasterDataFile.csv')      # to read the training data into working memory
df['feature'] = df['feature'].replace(to_replace='<.*>', value='', regex=True)

X_train, X_test, y_train, y_test = train_test_split(df['feature'],   # Test-Train Split function
                                                    df['target'],
                                                    train_size = 0.8,
                                                    test_size = 0.2,
                                                    random_state=14
                                                    )

vect = CountVectorizer(min_df=1,          # Minimum Document Frequency
                       ngram_range=(1, 2),   # unigrams to bigrams
                       stop_words='english',   # stopwords
                       lowercase =False,
                       binary = True
                       ).fit(X_train)
X_train_vectorized = vect.transform(X_train)
X_test_vectorized = vect.transform(X_test)

X_train_vectorized_tfidf = TfidfTransformer().fit_transform(X_train_vectorized) # or X_train_dense
X_test_vectorized_tfidf = TfidfTransformer().fit_transform(X_test_vectorized) # or X_test_dense

In [35]:
param_grid = {'C': [1, 10, 100, 1000], 'kernel': ['linear', 'rbf'], 'gamma': [0.001, 0.0001]}, {'C': [1, 10, 100, 1000], 'kernel': ['poly'], 'degree': [3, 4, 5], 'gamma': [0.001, 0.0001],}

In [36]:
svc = svm.SVC()
clf = GridSearchCV(svc, param_grid)

In [37]:
clf.fit(X_train_vectorized, y_train)


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1, param_grid={},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [38]:
clf.best_score_
clf.best_estimator_
clf.best_params_


{}

In [70]:
LSVCParam_Grid = ({'penalty': ['l2'], 'loss': ['squared_hinge'], 'dual': [True, False], 'C': [1, 100, 1000, 10000], 
                  'multi_class': ['ovr', 'crammer_singer'], 'max_iter': [1000, 2000, 8000]},
                  {'penalty': ['l2'], 'loss': ['hinge', 'squared_hinge'], 'dual': [True], 'C': [1, 100, 1000, 10000], 
                  'multi_class': ['ovr', 'crammer_singer'], 'max_iter': [1000, 2000, 8000]})

In [71]:
lsvc = LinearSVC()
clf2 = GridSearchCV(lsvc, LSVCParam_Grid)

In [72]:
clf2.fit(X_train_vectorized_tfidf, y_train)


GridSearchCV(cv=None, error_score='raise',
       estimator=LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=({'penalty': ['l2'], 'loss': ['squared_hinge'], 'dual': [True, False], 'C': [1, 100, 1000, 10000], 'multi_class': ['ovr', 'crammer_singer'], 'max_iter': [1000, 2000, 8000]}, {'penalty': ['l2'], 'loss': ['hinge', 'squared_hinge'], 'dual': [True], 'C': [1, 100, 1000, 10000], 'multi_class': ['ovr', 'crammer_singer'], 'max_iter': [1000, 2000, 8000]}),
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [74]:
clf2.best_score_



LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [75]:
clf2.best_estimator_

LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [84]:
clf2.best_params_


LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [ ]:

clf2.score(X_test_vectorized_tfidf, y_test


LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [101]:
ourlsvc = LinearSVC(C=1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='hinge', max_iter=1000, multi_class='ovr',
     penalty='l2', random_state=None, tol=0.0001, verbose=0).fit(X_train_vectorized, y_train)


LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [122]:
y_predict = ourlsvc.predict(X_test_vectorized)
y_test_compare = y_test.as_matrix()

LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [129]:
print('LinearSVC with parameters from GridSearchCV')
print('Accuracy: ', accuracy_score(y_test_compare, y_predict))
print('f1: ', f1_score(y_test_compare, y_predict))
print('Precision: ', precision_score(y_test_compare, y_predict))
print('Recall: ', recall_score(y_test_compare, y_predict))
print(classification_report(y_test_compare, y_predict))


LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [133]:
print('LinearSVC with parameters from GridSearchCV')
print('Accuracy: ', accuracy_score(y_test, y_predict))
print('f1: ', f1_score(y_test, y_predict))
print('Precision: ', precision_score(y_test, y_predict))
print('Recall: ', recall_score(y_test, y_predict))
print(classification_report(y_test, y_predict))

LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [135]:
print('LinearSVC with parameters from GridSearchCV')
print('Accuracy: ', accuracy_score(y_test, y_predict))
print('f1: ', f1_score(y_test, y_predict))
print('Precision: ', precision_score(y_test, y_predict, average='binary'))
print('Recall: ', recall_score(y_test, y_predict))
print(classification_report(y_test, y_predict))

LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [131]:
y_test_compare

LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [126]:
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [8]:
weighted_prediction = lsvc_model.predict(X_test_vectorized)


Accuracy: 0.89369592089
F1 score: 0.924445399285
Recall: 0.89369592089
Precision: 0.966897473066

 classification report:
              precision    recall  f1-score   support

          0       0.99      0.90      0.94       788
          1       0.14      0.62      0.23        21

avg / total       0.97      0.89      0.92       809


 confussion matrix:
 [[710  78]
 [  8  13]]


In [9]:
print ('Accuracy:', accuracy_score(y_test, weighted_prediction))
print ('F1 score:', f1_score(y_test, weighted_prediction,average='weighted'))
print ('Recall:', recall_score(y_test, weighted_prediction,
                              average='weighted'))
print ('Precision:', precision_score(y_test, weighted_prediction,
                                    average='weighted'))
print ('\n classification report:\n', classification_report(y_test, weighted_prediction))
print ('\n confussion matrix:\n',confusion_matrix(y_test, weighted_prediction))


Accuracy: 0.89369592089
F1 score: 0.924445399285
Recall: 0.89369592089
Precision: 0.966897473066

 classification report:
              precision    recall  f1-score   support

          0       0.99      0.90      0.94       788
          1       0.14      0.62      0.23        21

avg / total       0.97      0.89      0.92       809


 confussion matrix:
 [[710  78]
 [  8  13]]
