In [81]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import ParameterGrid
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import string
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer   # “Term Frequency times Inverse Document Frequency”
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB       # Multinomial Naive Bayes, supposedly goes well with the data from the transformer
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_fscore_support
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, classification_report, confusion_matrix
from sklearn.pipeline import make_union # used to combine multiple features
from sklearn.preprocessing import StandardScaler # used to fit and transform the vote counts
from sklearn.pipeline import FeatureUnion
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import maxabs_scale

In [82]:
df = pd.read_csv('C:\\Users\\maxjp\\PycharmProjects\\complingproject\\MasterDataFileVotes.csv')      # to read the training data into working memory
df['feature'] = df['feature'].replace(to_replace='<.*>', value='', regex=True)




In [102]:
X_train, X_test, y_train, y_test, Z_train, Z_test = train_test_split(df['feature'],   # Test-Train Split function
                                                    df['target'], 
                                                    df['vote'],
                                                    train_size = 0.8,
                                                    test_size = 0.2,
                                                    random_state=14
                                                    )

In [87]:
X_train

514     Thanks a lot for the steps. I got somehow lost...
548     StudentID is used to anonymize data (in place ...
1772    Pretty sure I've found the outliers, but if I ...
2275    only pdf.  ;But I discovered that I don't need...
3274    I couldn't agree more. I have a taken statisti...
905     Luc  ; Jason -- either of your interpretations...
1316    Hi Anant,  Here are two quick comments: 1) The...
1179    Hi. We'll discuss IRT in week 4 of the class. ...
1312    I downloaded the zip file and compiled and exe...
2753    What changes required to run linear regression...
2356    What I did Luc was to start out with the first...
2935    So everything should be OK if your answer in t...
259       Thanks to everyone who came! See you next time.
939     Hi Bassirou,  Did you make sure to connect the...
782     Hi, ;. I actually didn't need to register on t...
2242    To select he number k of clusters, we should "...
2960                        Sure... mine bikram.chitrakar
3097    Hi, Ho

In [88]:
Z_train

514     0
548     0
1772    0
2275    0
3274    1
905     0
1316    0
1179    0
1312    0
2753    0
2356    1
2935    0
259     0
939     0
782     0
2242    0
2960    0
3097    1
874     0
3523    1
273     0
667     3
3656    1
3178    0
2702    0
3023    0
3095    0
839     0
2319    2
3364    0
       ..
2149    1
1656    0
3621    2
2181    0
3156    0
470     0
1536    1
3722    0
3210    2
260     0
2592    1
2539    0
3062    0
471     0
1049    0
1690    0
3949    0
3560    0
2621    0
1232    1
1674    0
2716    0
746     0
3430    0
3833    0
2375    0
2454    0
1292    0
1368    0
2667    0
Name: vote, Length: 3235, dtype: int64

In [84]:
vect = CountVectorizer(min_df=1,          # Minimum Document Frequency
                       ngram_range=(1, 2),   # unigrams to bigrams
                       stop_words='english',   # stopwords
                       lowercase =False,
                       binary = True
                       ).fit(X_train)

X_train_vectorized = vect.transform(X_train)
X_test_vectorized = vect.transform(X_test)
]).fit_transform(X_train_vectorized) # or X_train_dense
X_test_vectorized_tfidf = TfidfTransformer().fit_transform(X_test_vectorized) # or X_test_dense

In [92]:
Z_traint = Z_train.reshape(-1, 1)
Z_testt = Z_train.reshape(-1, 1)
#fittransformZ = StandardScaler().fit(Z_traint)
#Z_train_transform = fittransformZ.transform(Z_traint)
#Z_test_transform = fittransformZ.transform(Z_testt)
Z_train_fit = StandardScaler().fit_transform(Z_traint)
# Z_train_transform = maxabs_scale(Z_train)
# Z_test_transform = maxabs_scale(Z_test)


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [93]:
X_train_vectorized

<3235x87594 sparse matrix of type '<class 'numpy.int64'>'
	with 174384 stored elements in Compressed Sparse Row format>

In [104]:
Z_train_fit

array([[-0.31548401],
       [-0.31548401],
       [-0.31548401],
       ..., 
       [-0.31548401],
       [-0.31548401],
       [-0.31548401]])

In [125]:
Z_trainReshape = Z_train.reshape(-1, 1)
feature_list = (('Vectorizer', 
                CountVectorizer(min_df=1,
                       ngram_range=(1, 2),
                       stop_words='english',
                       lowercase = False,
                       binary = True).fit_transform(X_train)),
                ('Scaler', StandardScaler().fit_transform(Z_trainReshape)))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """Entry point for launching an IPython kernel.


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [126]:
X_train = FeatureUnion(feature_list)

TypeError: All estimators should implement fit and transform. '  (0, 45116)	1
  (0, 75074)	1
  (0, 33995)	1
  (0, 27028)	1
  (0, 12984)	1
  (0, 57054)	1
  (0, 35125)	1
  (0, 68619)	1
  (0, 29736)	1
  (0, 79734)	1
  (0, 11018)	1
  (0, 64437)	1
  (0, 54736)	1
  (0, 45492)	1
  (0, 75607)	1
  (0, 54841)	1
  (0, 18800)	1
  (0, 6442)	1
  (0, 45112)	1
  (0, 75044)	1
  (0, 33690)	1
  (0, 27001)	1
  (0, 12973)	1
  (0, 57043)	1
  (0, 34800)	1
  :	:
  (3234, 57348)	1
  (3234, 72205)	1
  (3234, 18603)	1
  (3234, 34180)	1
  (3234, 18901)	1
  (3234, 20543)	1
  (3234, 57344)	1
  (3234, 78280)	1
  (3234, 69039)	1
  (3234, 60323)	1
  (3234, 76473)	1
  (3234, 18814)	1
  (3234, 55382)	1
  (3234, 18578)	1
  (3234, 72172)	1
  (3234, 18856)	1
  (3234, 73078)	1
  (3234, 20531)	1
  (3234, 55358)	1
  (3234, 47000)	1
  (3234, 27710)	1
  (3234, 66666)	1
  (3234, 79317)	1
  (3234, 77191)	1
  (3234, 18670)	1' (type <class 'scipy.sparse.csr.csr_matrix'>) doesn't

In [20]:
param_grid = {'C': [1, 10, 100, 1000], 'kernel': ['linear', 'rbf'], 'gamma': [0.001, 0.0001]}, {'C': [1, 10, 100, 1000], 'kernel': ['poly'], 'degree': [3, 4, 5], 'gamma': [0.001, 0.0001],}

In [ ]:
example_model = svm.SVC().fit(X_train_vectorized, y_train)



y_prediction = example_model.predict(, skdfj;lj)

In [36]:
svc = svm.SVC()
clf = GridSearchCV(svc, param_grid)

In [37]:
clf.fit(X_train_vectorized, y_train)


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1, param_grid={},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [136]:
clf.best_score_
clf.best_estimator_
clf.best_params_


{}

In [70]:
LSVCParam_Grid = ({'penalty': ['l2'], 'loss': ['squared_hinge'], 'dual': [True, False], 'C': [1, 100, 1000, 10000], 
                  'multi_class': ['ovr', 'crammer_singer'], 'max_iter': [1000, 2000, 8000]},
                  {'penalty': ['l2'], 'loss': ['hinge', 'squared_hinge'], 'dual': [True], 'C': [1, 100, 1000, 10000], 
                  'multi_class': ['ovr', 'crammer_singer'], 'max_iter': [1000, 2000, 8000]})

In [71]:
lsvc = LinearSVC()
clf2 = GridSearchCV(lsvc, LSVCParam_Grid)

In [72]:
clf2.fit(X_train_vectorized_tfidf, y_train)


GridSearchCV(cv=None, error_score='raise',
       estimator=LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=({'penalty': ['l2'], 'loss': ['squared_hinge'], 'dual': [True, False], 'C': [1, 100, 1000, 10000], 'multi_class': ['ovr', 'crammer_singer'], 'max_iter': [1000, 2000, 8000]}, {'penalty': ['l2'], 'loss': ['hinge', 'squared_hinge'], 'dual': [True], 'C': [1, 100, 1000, 10000], 'multi_class': ['ovr', 'crammer_singer'], 'max_iter': [1000, 2000, 8000]}),
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [74]:
clf2.best_score_



LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [75]:
clf2.best_estimator_

LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [84]:
clf2.best_params_


LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [ ]:

clf2.score(X_test_vectorized_tfidf, y_test


LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [101]:
ourlsvc = LinearSVC(C=1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='hinge', max_iter=1000, multi_class='ovr',
     penalty='l2', random_state=None, tol=0.0001, verbose=0).fit(X_train_vectorized, y_train)


LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [122]:
y_predict = ourlsvc.predict(X_test_vectorized)
y_test_compare = y_test.as_matrix()

LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [129]:
print('LinearSVC with parameters from GridSearchCV')
print('Accuracy: ', accuracy_score(y_test_compare, y_predict))
print('f1: ', f1_score(y_test_compare, y_predict))
print('Precision: ', precision_score(y_test_compare, y_predict))
print('Recall: ', recall_score(y_test_compare, y_predict))
print(classification_report(y_test_compare, y_predict))


LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [133]:
print('LinearSVC with parameters from GridSearchCV')
print('Accuracy: ', accuracy_score(y_test, y_predict))
print('f1: ', f1_score(y_test, y_predict))
print('Precision: ', precision_score(y_test, y_predict))
print('Recall: ', recall_score(y_test, y_predict))
print(classification_report(y_test, y_predict))

LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [135]:
print('LinearSVC with parameters from GridSearchCV')
print('Accuracy: ', accuracy_score(y_test, y_predict))
print('f1: ', f1_score(y_test, y_predict))
print('Precision: ', precision_score(y_test, y_predict, average='binary'))
print('Recall: ', recall_score(y_test, y_predict))
print(classification_report(y_test, y_predict))

LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [131]:
y_test_compare

LinearSVC with parameters from GridSearchCV
Accuracy:  0.974042027194
f1:  0.16
Precision:  0.5
Recall:  0.0952380952381
             precision    recall  f1-score   support

          0       0.98      1.00      0.99       788
          1       0.50      0.10      0.16        21

avg / total       0.96      0.97      0.97       809



In [126]:
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

Accuracy: 0.89369592089
F1 score: 0.924445399285
Recall: 0.89369592089
Precision: 0.966897473066

 classification report:
              precision    recall  f1-score   support

          0       0.99      0.90      0.94       788
          1       0.14      0.62      0.23        21

avg / total       0.97      0.89      0.92       809


 confussion matrix:
 [[710  78]
 [  8  13]]


Accuracy: 0.89369592089
F1 score: 0.924445399285
Recall: 0.89369592089
Precision: 0.966897473066

 classification report:
              precision    recall  f1-score   support

          0       0.99      0.90      0.94       788
          1       0.14      0.62      0.23        21

avg / total       0.97      0.89      0.92       809


 confussion matrix:
 [[710  78]
 [  8  13]]
